async function main() {
  try {
  } catch (error) {
    console.error(error)
  }
}

console.log('Execution started')
main().then(() => {
  console.log('Execution finished')
})
